### ISSUE TITLE
Shell Injection Vulnerability in File Upload

### ISSUE THREAD

**Issue by craigmc08** [joshua-coppola/print-server#1]
A specially crafted filename could likely be used to run a user-selected shell command. In combination with being able to upload files to a deterministic location, it's likely easy to run whatever code you want to on the server with no permission.

Relevant line of code: https://github.com/joshua-coppola/print-server/commit/8aa23a70d2188526801c83b6a0d0a2549d2f492f#diff-b10564ab7d2c520cdd0243874879fb0a782862c3c902ab535faabe57d5a505e1R43

**Comment by joshua-coppola** [comment]
Fixed in latest commit
